language: c
matrix:
  include:
    # macOS
    - env: TARGET_MACHINE=i3osx
      os: osx
    - env: TARGET_MACHINE=ti3osx
      os: osx
    - env: TARGET_MACHINE=a6osx
      os: osx
    - env: TARGET_MACHINE=ta6osx
      os: osx

    # Linux
    - env: TARGET_MACHINE=i3le
      os: linux
      addons:
        apt:
          packages:
            - gcc-multilib
            - lib32ncurses5-dev
            - libx32ncurses5-dev
            - uuid-dev:i386
    - env: TARGET_MACHINE=ti3le
      os: linux
      addons:
        apt:
          packages:
            - gcc-multilib
            - lib32ncurses5-dev
            - libx32ncurses5-dev
            - uuid-dev:i386
    - env: TARGET_MACHINE=a6le
      os: linux
    - env: TARGET_MACHINE=ta6le
      os: linux

    # Windows
    - env: TARGET_MACHINE=i3nt
      os: windows
      before_script:
        - git config core.autocrlf false; rm .git/index; git reset --hard
        - choco install make -y
    - env: TARGET_MACHINE=ti3nt
      os: windows
      before_script:
        - git config core.autocrlf false; rm .git/index; git reset --hard
        - choco install make -y
    - env: TARGET_MACHINE=a6nt
      os: windows
      before_script:
        - git config core.autocrlf false; rm .git/index; git reset --hard
        - choco install make -y
    - env: TARGET_MACHINE=ta6nt
      os: windows
      before_script:
        - git config core.autocrlf false; rm .git/index; git reset --hard
        - choco install make -y
dist: xenial
script:
  - .travis/build.sh
  - .travis/test.sh
