name: Build CI

on: [push, pull_request]

jobs:
  
  build-linux:
    runs-on: ubuntu-18.04
    
    strategy:
      fail-fast: false
      matrix:
        mach: ['ta6le'] 

    env:
      TARGET_MACHINE: ${{ matrix.mach }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Proceed with TARGET_MACHINE == ${{ matrix.mach }}
        run: echo $TARGET_MACHINE
      - name: Install libs for 32-bit
        if: matrix.mach == 'i3le' || matrix.mach == 'ti3le'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y gcc-multilib lib32ncurses5-dev libx32ncurses5-dev uuid-dev:i386 libssl-dev:i386
      - name: Install libs for 64-bit
        if: matrix.mach == 'a6le' || matrix.mach == 'ta6le'
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses5-dev uuid-dev libssl-dev
      - name: Build bootfiles
        run: .github/scripts/dobootfile.sh
      - name: Build Chez
        run: .github/scripts/build.sh
      - name: Test Chez
        run: .github/scripts/test.sh
